version: "3.8"

services:
  api:
    image: drupal 
    container_name: api 
    pull_policy: always
    restart: always
    networks:
       - traefik
       - backend
    ports:
      - "80"
    volumes:
      - drupal-data:/var/www/html
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.api.rule=Host(`api.njitstudentmarketplace.me`) 
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=simple-resolver
      - traefik.http.services.api.loadbalancer.server.port=80
networks:
  traefik:
      name: traefik
      external: true
  backend:
      external: true
volumes:
  postgres-data:
    driver: local

  drupal-data:
    driver: local
